

services:
  torun_backend:
    build: .
    container_name: torun_container
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads         
      - ./torun_sistemi.db:/app/torun_sistemi.db 
    env_file:
      - .env                         
    restart: always